# Stage 1: Build
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

# Copy parent POM
COPY pom.xml .

# Copy tất cả pom.xml của các module
COPY discovery-service/pom.xml ./discovery-service/
COPY api-gateway/pom.xml ./api-gateway/
COPY user-service/pom.xml ./user-service/
COPY subject-service/pom.xml ./subject-service/

# Download dependencies
RUN mvn dependency:go-offline -B -N

# Copy source code
COPY api-gateway/src ./api-gateway/src

# Build chỉ module api-gateway
RUN mvn clean package -DskipTests -pl api-gateway

# Stage 2: Run
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/api-gateway/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]