# Stage 1: Build
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

# Copy parent POM
COPY pom.xml .

# Copy tất cả pom.xml của các module
COPY discovery-service/pom.xml ./discovery-service/
COPY api-gateway/pom.xml ./api-gateway/
COPY user-service/pom.xml ./user-service/
COPY subject-service/pom.xml ./subject-service/

# Download dependencies
RUN mvn dependency:go-offline -B -N

# Copy source code
COPY subject-service/src ./subject-service/src

# Build chỉ module subject-service
RUN mvn clean package -DskipTests -pl subject-service

# Stage 2: Run
FROM eclipse-temurin:17-jre-alpine
RUN apk add --no-cache wget netcat-openbsd
WORKDIR /app
COPY --from=build /app/subject-service/target/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]